import React,{createContext,useContext,useEffect,useMemo,useState} from 'react';
import { CoupleNote, Expense, HouseholdTask, Member } from '../types';
import { demoExpenses,demoMembers,demoNotes,demoTasks } from '../data/demo';
import { supabase } from '../services/supabase';
type AppState={currentUserId:string;members:Member[];expenses:Expense[];tasks:HouseholdTask[];notes:CoupleNote[];addExpense:(x:Expense)=>void;removeExpense:(id:string)=>void;addTask:(x:HouseholdTask)=>void;completeTask:(id:string,by:string)=>void;addNote:(x:CoupleNote)=>void;toggleFavorite:(id:string)=>void;readNote:(id:string)=>void;archiveNote:(id:string)=>void};
const Context=createContext<AppState|null>(null);
export function AppProvider({children,demo=true}:{children:React.ReactNode;demo?:boolean}){
 const [currentUserId,setCurrentUserId]=useState(demo?'jessica':'');const [groupId,setGroupId]=useState(demo?'demo':'');const [members,setMembers]=useState<Member[]>(demo?demoMembers:[]);const [expenses,setExpenses]=useState<Expense[]>(demo?demoExpenses:[]);const [tasks,setTasks]=useState<HouseholdTask[]>(demo?demoTasks:[]);const [notes,setNotes]=useState<CoupleNote[]>(demo?demoNotes:[]);
 useEffect(()=>{if(demo)return;void(async()=>{const {data:{user}}=await supabase.auth.getUser();if(!user)return;setCurrentUserId(user.id);const {data:membership}=await supabase.from('group_members').select('group_id').eq('user_id',user.id).maybeSingle();if(!membership)return;setGroupId(membership.group_id);const [{data:ms},{data:es},{data:ts},{data:ns}]=await Promise.all([supabase.from('group_members').select('user_id').eq('group_id',membership.group_id),supabase.from('expenses').select('*, expense_splits(*)').eq('group_id',membership.group_id).order('expense_date',{ascending:false}),supabase.from('household_tasks').select('*').eq('group_id',membership.group_id).order('task_date'),supabase.from('couple_notes').select('*').eq('group_id',membership.group_id).neq('status','deleted').order('created_at',{ascending:false})]);const ids=(ms??[]).map(x=>x.user_id);const {data:profiles}=ids.length?await supabase.from('users_profile').select('user_id,name,email').in('user_id',ids):{data:[]};const mapped=(profiles??[]) as Member[];setMembers(mapped);setExpenses((es??[]).map((e:any)=>({...e,payer_name:mapped.find(m=>m.user_id===e.paid_by)?.name,expense_splits:e.expense_splits.map((s:any)=>({...s,user_name:mapped.find(m=>m.user_id===s.user_id)?.name}))})));setTasks((ts??[]).map((t:any)=>({...t,assigned_name:t.assigned_to==='both'?'Ambos':mapped.find(m=>m.user_id===t.assigned_to)?.name,completed_name:t.completed_by==='both'?'Ambos':mapped.find(m=>m.user_id===t.completed_by)?.name})));setNotes((ns??[]).map((n:any)=>({...n,author_name:mapped.find(m=>m.user_id===n.author_id)?.name,recipient_name:n.recipient_id==='both'?'Ambos':mapped.find(m=>m.user_id===n.recipient_id)?.name})));})();},[demo]);
 const addExpense=(x:Expense)=>{if(demo){setExpenses(v=>[x,...v]);return}void(async()=>{const {id,expense_splits,...row}=x;const {data,error}=await supabase.from('expenses').insert({...row,group_id:groupId,created_by:currentUserId}).select().single();if(error)return;await supabase.from('expense_splits').insert(expense_splits.map(({user_name,...s})=>({...s,expense_id:data.id})));setExpenses(v=>[{...x,id:data.id,group_id:groupId},...v])})()};
 const addTask=(x:HouseholdTask)=>{if(demo){setTasks(v=>[x,...v]);return}void(async()=>{const {id,assigned_name,completed_name,...row}=x;const {data}=await supabase.from('household_tasks').insert({...row,group_id:groupId,created_by:currentUserId}).select().single();if(data)setTasks(v=>[{...x,id:data.id,group_id:groupId},...v])})()};
 const addNote=(x:CoupleNote)=>{if(demo){setNotes(v=>[x,...v]);return}void(async()=>{const {id,author_name,recipient_name,...row}=x;const {data}=await supabase.from('couple_notes').insert({...row,group_id:groupId,author_id:currentUserId}).select().single();if(data)setNotes(v=>[{...x,id:data.id,group_id:groupId},...v])})()};
 const value=useMemo<AppState>(()=>({currentUserId,members,expenses,tasks,notes,addExpense,removeExpense:id=>{setExpenses(v=>v.filter(x=>x.id!==id));if(!demo)void supabase.from('expenses').delete().eq('id',id)},addTask,completeTask:(id,by)=>{const update={status:'completed' as const,completed_by:by,completed_at:new Date().toISOString()};setTasks(v=>v.map(x=>x.id===id?{...x,...update,completed_name:by==='both'?'Ambos':members.find(m=>m.user_id===by)?.name}:x));if(!demo)void supabase.from('household_tasks').update(update).eq('id',id)},addNote,toggleFavorite:id=>{const n=notes.find(x=>x.id===id);setNotes(v=>v.map(x=>x.id===id?{...x,is_favorite:!x.is_favorite}:x));if(!demo&&n)void supabase.from('couple_notes').update({is_favorite:!n.is_favorite}).eq('id',id)},readNote:id=>{setNotes(v=>v.map(x=>x.id===id?{...x,is_read:true,read_at:new Date().toISOString()}:x));if(!demo)void supabase.from('couple_notes').update({is_read:true,read_at:new Date().toISOString()}).eq('id',id)},archiveNote:id=>{setNotes(v=>v.map(x=>x.id===id?{...x,status:'archived'}:x));if(!demo)void supabase.from('couple_notes').update({status:'archived'}).eq('id',id)}}),[currentUserId,members,expenses,tasks,notes,demo,groupId]);return <Context.Provider value={value}>{children}</Context.Provider>}
export const useApp=()=>{const v=useContext(Context);if(!v)throw new Error('AppProvider faltante');return v;};
