import React from 'react';
import { ActivityIndicator, Pressable, StyleSheet, Text, TextInput, TextInputProps, View, ViewStyle } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { colors, radius, shadow } from '../theme';
export function Card({children,style}:{children:React.ReactNode;style?:ViewStyle}){return <View style={[s.card,style]}>{children}</View>}
export function SectionHeader({title,action,onPress}:{title:string;action?:string;onPress?:()=>void}){return <View style={s.row}><Text style={s.section}>{title}</Text>{action&&<Pressable accessibilityRole="button" onPress={onPress} hitSlop={10}><Text style={s.link}>{action}</Text></Pressable>}</View>}
export function PrimaryButton({label,onPress,loading=false,variant='primary',icon}:{label:string;onPress:()=>void;loading?:boolean;variant?:'primary'|'soft'|'danger';icon?:keyof typeof Ionicons.glyphMap}){return <Pressable accessibilityRole="button" disabled={loading} onPress={onPress} style={({pressed})=>[s.button,variant==='soft'&&s.soft,variant==='danger'&&s.danger,pressed&&{opacity:.82}]}>{loading?<ActivityIndicator color={colors.white}/>:<><Ionicons name={icon??'arrow-forward'} size={19} color={variant==='soft'?colors.primary:colors.white}/><Text style={[s.buttonText,variant==='soft'&&{color:colors.primary}]}>{label}</Text></>}</Pressable>}
export function Field({label,error,...props}:TextInputProps&{label:string;error?:string}){return <View style={{gap:6}}><Text style={s.label}>{label}</Text><TextInput placeholderTextColor="#84918F" style={[s.input,error&&{borderColor:colors.danger}]} {...props}/>{error&&<Text style={s.error}>{error}</Text>}</View>}
export function Pill({label,active,onPress}:{label:string;active?:boolean;onPress?:()=>void}){return <Pressable accessibilityRole="button" onPress={onPress} style={[s.pill,active&&s.pillActive]}><Text style={[s.pillText,active&&{color:colors.white}]}>{label}</Text></Pressable>}
export function EmptyState({title,body}:{title:string;body:string}){return <Card style={{alignItems:'center',gap:6}}><Ionicons name="leaf-outline" size={28} color={colors.primary}/><Text style={s.section}>{title}</Text><Text style={s.muted}>{body}</Text></Card>}
const s=StyleSheet.create({card:{backgroundColor:colors.surface,borderRadius:radius.md,padding:16,borderWidth:1,borderColor:colors.border,...shadow},row:{flexDirection:'row',justifyContent:'space-between',alignItems:'center'},section:{fontSize:19,fontWeight:'700',color:colors.ink},link:{fontSize:15,fontWeight:'700',color:colors.primary},button:{minHeight:50,borderRadius:radius.md,backgroundColor:colors.primary,flexDirection:'row',gap:9,alignItems:'center',justifyContent:'center',paddingHorizontal:18},soft:{backgroundColor:colors.primarySoft},danger:{backgroundColor:colors.danger},buttonText:{fontSize:16,fontWeight:'700',color:colors.white},label:{fontSize:14,fontWeight:'700',color:colors.ink},input:{minHeight:50,borderWidth:1,borderColor:colors.border,borderRadius:radius.sm,paddingHorizontal:14,fontSize:16,color:colors.ink,backgroundColor:colors.surface},error:{fontSize:13,color:colors.danger},pill:{minHeight:42,paddingHorizontal:14,borderRadius:22,borderWidth:1,borderColor:colors.border,alignItems:'center',justifyContent:'center',backgroundColor:colors.surface},pillActive:{backgroundColor:colors.primary,borderColor:colors.primary},pillText:{color:colors.ink,fontWeight:'600'},muted:{fontSize:15,lineHeight:22,color:colors.muted,textAlign:'center'}});
export const ui=s;
