-- Hogar MVP · ejecutar completo en Supabase SQL Editor
create extension if not exists pgcrypto;
create type public.split_type as enum ('equal','percentage','fixed','individual');
create type public.task_frequency as enum ('once','daily','weekly','biweekly','monthly');
create type public.task_status as enum ('pending','completed','overdue');
create type public.note_status as enum ('visible','archived','deleted');

create table public.users_profile (id uuid primary key default gen_random_uuid(), user_id uuid unique not null references auth.users on delete cascade, name text not null, email text not null, created_at timestamptz default now(), updated_at timestamptz default now());
create table public.groups (id uuid primary key default gen_random_uuid(), name text not null, invite_code text unique not null default upper(substr(encode(gen_random_bytes(6),'hex'),1,6)), created_by uuid not null references auth.users, created_at timestamptz default now(), updated_at timestamptz default now());
create table public.group_members (id uuid primary key default gen_random_uuid(), group_id uuid not null references public.groups on delete cascade, user_id uuid not null references auth.users on delete cascade, role text not null default 'member' check(role in ('owner','member')), joined_at timestamptz default now(), unique(group_id,user_id));
create table public.expenses (id uuid primary key default gen_random_uuid(), group_id uuid not null references public.groups on delete cascade, paid_by uuid not null references auth.users, amount numeric(12,0) not null check(amount>0), category text not null, description text not null, expense_date date not null, split_type public.split_type not null, notes text, created_by uuid not null default auth.uid() references auth.users, created_at timestamptz default now(), updated_at timestamptz default now());
create table public.expense_splits (id uuid primary key default gen_random_uuid(), expense_id uuid not null references public.expenses on delete cascade, user_id uuid not null references auth.users, amount_owed numeric(12,0) not null check(amount_owed>=0), percentage numeric(5,2) check(percentage between 0 and 100), created_at timestamptz default now(), unique(expense_id,user_id));
create table public.settlements (id uuid primary key default gen_random_uuid(), group_id uuid not null references public.groups on delete cascade, from_user_id uuid not null references auth.users, to_user_id uuid not null references auth.users, amount numeric(12,0) not null check(amount>0), status text not null default 'pending' check(status in ('pending','paid')), month date not null, created_at timestamptz default now(), paid_at timestamptz);
create table public.household_tasks (id uuid primary key default gen_random_uuid(), group_id uuid not null references public.groups on delete cascade, title text not null, description text, task_date date not null, frequency public.task_frequency not null default 'once', assigned_to text not null, completed_by text, status public.task_status not null default 'pending', completed_at timestamptz, notes text, created_by uuid not null default auth.uid() references auth.users, created_at timestamptz default now(), updated_at timestamptz default now());
create table public.task_history (id uuid primary key default gen_random_uuid(), task_id uuid not null references public.household_tasks on delete cascade, group_id uuid not null references public.groups on delete cascade, assigned_to text not null, completed_by text, status public.task_status not null, scheduled_date date not null, completed_at timestamptz, created_at timestamptz default now());
create table public.couple_notes (id uuid primary key default gen_random_uuid(), group_id uuid not null references public.groups on delete cascade, author_id uuid not null default auth.uid() references auth.users, recipient_id text not null, title text, message text not null check(length(trim(message))>0), category text, emoji text, status public.note_status not null default 'visible', is_favorite boolean not null default false, is_read boolean not null default false, read_at timestamptz, created_at timestamptz default now(), updated_at timestamptz default now());
create table public.monthly_closures (id uuid primary key default gen_random_uuid(), group_id uuid not null references public.groups on delete cascade, month date not null, total_expenses numeric(12,0) default 0, total_paid_by_jessica numeric(12,0) default 0, total_paid_by_mateo numeric(12,0) default 0, total_owed_by_jessica numeric(12,0) default 0, total_owed_by_mateo numeric(12,0) default 0, final_balance_message text, tasks_completed_by_jessica int default 0, tasks_completed_by_mateo int default 0, pending_tasks int default 0, overdue_tasks int default 0, notes_sent_by_jessica int default 0, notes_sent_by_mateo int default 0, favorite_notes_count int default 0, status text not null default 'pending' check(status in ('pending','paid')), created_at timestamptz default now(), updated_at timestamptz default now(), unique(group_id,month));

create or replace function public.is_group_member(target_group uuid) returns boolean language sql stable security definer set search_path=public as $$ select exists(select 1 from group_members where group_id=target_group and user_id=auth.uid()) $$;
create or replace function public.join_group(code text) returns uuid language plpgsql security definer set search_path=public as $$ declare gid uuid; begin select id into gid from groups where invite_code=upper(trim(code)); if gid is null then raise exception 'Código inválido'; end if; if (select count(*) from group_members where group_id=gid)>=2 then raise exception 'Este hogar ya tiene dos integrantes'; end if; insert into group_members(group_id,user_id) values(gid,auth.uid()) on conflict do nothing; return gid; end $$;
create or replace function public.create_group(group_name text) returns table(group_id uuid, invite_code text) language plpgsql security definer set search_path=public as $$ declare g groups; begin if auth.uid() is null then raise exception 'Debes iniciar sesión'; end if; if exists(select 1 from group_members where user_id=auth.uid()) then raise exception 'Ya perteneces a un hogar'; end if; insert into groups(name,created_by) values(coalesce(nullif(trim(group_name),''),'Nuestro hogar'),auth.uid()) returning * into g; insert into group_members(group_id,user_id,role) values(g.id,auth.uid(),'owner'); return query select g.id,g.invite_code; end $$;
create or replace function public.handle_new_user() returns trigger language plpgsql security definer set search_path=public as $$ begin insert into users_profile(user_id,name,email) values(new.id,coalesce(new.raw_user_meta_data->>'name','Persona'),new.email);return new;end $$;
create trigger on_auth_user_created after insert on auth.users for each row execute function public.handle_new_user();
create or replace function public.limit_group_size() returns trigger language plpgsql as $$ begin if (select count(*) from group_members where group_id=new.group_id)>=2 then raise exception 'Un hogar admite máximo dos integrantes';end if;return new;end $$;
create trigger enforce_group_size before insert on public.group_members for each row execute function public.limit_group_size();

alter table users_profile enable row level security; alter table groups enable row level security; alter table group_members enable row level security; alter table expenses enable row level security; alter table expense_splits enable row level security; alter table settlements enable row level security; alter table household_tasks enable row level security; alter table task_history enable row level security; alter table couple_notes enable row level security; alter table monthly_closures enable row level security;
create policy profiles_self_or_couple on users_profile for select using(user_id=auth.uid() or exists(select 1 from group_members me join group_members them on them.group_id=me.group_id where me.user_id=auth.uid() and them.user_id=users_profile.user_id));
create policy profiles_update_self on users_profile for update using(user_id=auth.uid()) with check(user_id=auth.uid());
create policy groups_select_member on groups for select using(is_group_member(id));
create policy groups_create on groups for insert with check(created_by=auth.uid());
create policy groups_update_member on groups for update using(is_group_member(id));
create policy members_select_same_group on group_members for select using(is_group_member(group_id));
create policy members_insert_self on group_members for insert with check(user_id=auth.uid());
create policy expenses_member_all on expenses for all using(is_group_member(group_id)) with check(is_group_member(group_id) and created_by=auth.uid());
create policy splits_member_select on expense_splits for select using(exists(select 1 from expenses e where e.id=expense_id and is_group_member(e.group_id)));
create policy splits_member_insert on expense_splits for insert with check(exists(select 1 from expenses e where e.id=expense_id and is_group_member(e.group_id)));
create policy splits_member_update on expense_splits for update using(exists(select 1 from expenses e where e.id=expense_id and is_group_member(e.group_id)));
create policy splits_member_delete on expense_splits for delete using(exists(select 1 from expenses e where e.id=expense_id and is_group_member(e.group_id)));
create policy settlements_member_all on settlements for all using(is_group_member(group_id)) with check(is_group_member(group_id));
create policy tasks_member_all on household_tasks for all using(is_group_member(group_id)) with check(is_group_member(group_id));
create policy history_member_all on task_history for all using(is_group_member(group_id)) with check(is_group_member(group_id));
create policy notes_member_select on couple_notes for select using(is_group_member(group_id));
create policy notes_member_insert on couple_notes for insert with check(is_group_member(group_id) and author_id=auth.uid());
create policy notes_author_update on couple_notes for update using(is_group_member(group_id) and (author_id=auth.uid() or recipient_id=auth.uid()::text or recipient_id='both')) with check(is_group_member(group_id));
create policy notes_author_delete on couple_notes for delete using(is_group_member(group_id) and author_id=auth.uid());
create policy closures_member_all on monthly_closures for all using(is_group_member(group_id)) with check(is_group_member(group_id));
grant execute on function public.join_group(text) to authenticated;
grant execute on function public.create_group(text) to authenticated;
